version: "3"
services:
  client:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
 
    volumes:
      - ./frontend:/app/
      - /app/node_modules
  
  server:
    build:
      context: ./backend
    ports:
      - "5001:8000"
    # volumes:
      # - ./backend:/app
      # - /app/node_modules
    depends_on:
      - db
 
  db:
    build:
      context: ./db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-volume:



  